osx_image: xcode10.1
language: swift

script:
- swiftlint lint --strict
- xcodebuild clean build -sdk iphonesimulator -workspace Ororo-Player.xcworkspace -scheme Ororo-KitTests CODE_SIGNING_REQUIRED=NO -destination 'platform=iOS Simulator,name=iPhone XS Max,OS=12.1' test
